#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
FRAMEWORK="$ROOT/.flywheel/scripts/mp-validator-framework.sh"
VALIDATORS="$ROOT/.flywheel/scripts/mp-validators"
TMP="$(mktemp -d "${TMPDIR:-/tmp}/mp-validator-framework.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT

pass_count=0
fail_count=0
pass(){ pass_count=$((pass_count + 1)); printf 'PASS %s\n' "$1"; }
fail(){ fail_count=$((fail_count + 1)); printf 'FAIL %s\n' "$1" >&2; }
assert_jq(){ local file="$1" expr="$2" label="$3"; if jq -e "$expr" "$file" >/dev/null; then pass "$label"; else fail "$label"; jq . "$file" >&2 || true; fi; }

mkdir -p "$TMP/repo/tests/fixtures/case-a" "$TMP/repo/bin" "$TMP/repo/docs" "$TMP/repo/evidence" "$TMP/repo/policies"
cat >"$TMP/repo/tests/fixtures/case-a/PROVENANCE.md" <<'EOF'
# Provenance
Generated by tests/mp-validator-framework.sh.
EOF
cat >"$TMP/repo/tests/fixtures/PROVENANCE.md" <<'EOF'
# Provenance
Fixture root generated by tests/mp-validator-framework.sh.
EOF
cat >"$TMP/repo/bin/good-cli.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
case "${1:-}" in
  capabilities) jq -nc '{schema_version:"fixture.capabilities/v1",features:["json_output"],exit_codes:{"0":"success"}}' ;;
  robot-docs) printf 'agent handbook\n' ;;
  doctor|health|repair|validate|audit|why) jq -nc --arg command "${1:-}" '{schema_version:"fixture.cli/v1",command:$command,status:"pass"}' ;;
  *) printf 'unknown\n' >&2; exit 64 ;;
esac
EOF
chmod +x "$TMP/repo/bin/good-cli.sh"
cat >"$TMP/repo/bin/bad-cli.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
case "${1:-}" in
  doctor) printf '{}\n' ;;
  *) printf 'unknown\n' >&2; exit 64 ;;
esac
EOF
chmod +x "$TMP/repo/bin/bad-cli.sh"
cat >"$TMP/repo/docs/method.md" <<'EOF'
# Method

| Never | Why | Fix |
|---|---|---|
| Trust claims without receipts | Claims drift | Require evidence |
EOF
cat >"$TMP/repo/evidence/pack.md" <<'EOF'
# Evidence Pack

Manifest entries include sha256 hashes and schema_version constants. The pack is append-only with lineage, deterministic replay verification, and a refusal path for missing or malformed members.
EOF
cat >"$TMP/repo/policies/human-gate.md" <<'EOF'
# Risk Gate

The workflow defines confidence thresholds, risk tiers, approval context, escalation timeout rules, override metrics, and when automation can proceed alone.
EOF
cat >"$TMP/repo/policies/sandbox.md" <<'EOF'
# Authorized Sandbox

Written scope is required. The sandbox envelope records execution-layer authorization, least-privilege credentials, deny-by-default egress, output scanning, audit trails, and human approval for boundary expansion.
EOF

if bash -n "$FRAMEWORK"; then pass "framework syntax"; else fail "framework syntax"; fi
validator_count="$(find "$VALIDATORS" -maxdepth 1 -name 'MP-*-validator.sh' | wc -l | tr -d ' ')"
[[ "$validator_count" == "30" ]] && pass "thirty validators present" || fail "thirty validators present got=$validator_count"

for v in "$VALIDATORS"/MP-*-validator.sh; do
  bash -n "$v" && pass "syntax $(basename "$v")" || fail "syntax $(basename "$v")"
done

"$FRAMEWORK" --json MP-02 "$TMP/repo" >"$TMP/mp02.json"
assert_jq "$TMP/mp02.json" '.summary.pass == 1 and .summary.fail == 0' "MP-02 fixture provenance pass"

"$FRAMEWORK" --json MP-03 "$TMP/repo/bin/good-cli.sh" >"$TMP/mp03-good.json"
assert_jq "$TMP/mp03-good.json" '.summary.pass == 1 and .rows[0].status == "PASS"' "MP-03 good CLI pass"

set +e
"$FRAMEWORK" --json MP-03 "$TMP/repo/bin/bad-cli.sh" >"$TMP/mp03-bad.json"
rc=$?
set -e
[[ "$rc" -eq 1 ]] && pass "MP-03 bad CLI exits fail" || fail "MP-03 bad CLI exits fail rc=$rc"
assert_jq "$TMP/mp03-bad.json" '.summary.fail == 1 and (.rows[0].reason | test("lacks"))' "MP-03 bad CLI reason"

"$FRAMEWORK" --json MP-15 "$TMP/repo/bin/good-cli.sh" >"$TMP/mp15-good.json"
assert_jq "$TMP/mp15-good.json" '.summary.pass == 1 and .summary.coverage_ratio == 1' "MP-15 canonical CLI pass"

set +e
"$FRAMEWORK" --json MP-15 "$TMP/repo/bin/bad-cli.sh" >"$TMP/mp15-bad.json"
rc=$?
set -e
[[ "$rc" -eq 1 ]] && pass "MP-15 bad CLI exits fail" || fail "MP-15 bad CLI exits fail rc=$rc"
assert_jq "$TMP/mp15-bad.json" '.summary.fail == 1 and (.rows[0].reason | test("missing canonical"))' "MP-15 bad CLI reason"

"$FRAMEWORK" --json MP-22 "$TMP/repo/docs/method.md" >"$TMP/mp22.json"
assert_jq "$TMP/mp22.json" '.summary.pass == 1' "MP-22 negative table pass"

"$FRAMEWORK" --json MP-88 "$TMP/repo/evidence/pack.md" >"$TMP/mp88.json"
assert_jq "$TMP/mp88.json" '.summary.pass == 1 and .rows[0].status == "PASS"' "MP-88 content-addressed evidence pass"

"$FRAMEWORK" --json MP-94 "$TMP/repo/policies/human-gate.md" >"$TMP/mp94.json"
assert_jq "$TMP/mp94.json" '.summary.pass == 1 and .rows[0].status == "PASS"' "MP-94 risk-proportional human gate pass"

"$FRAMEWORK" --json MP-99 "$TMP/repo/policies/sandbox.md" >"$TMP/mp99.json"
assert_jq "$TMP/mp99.json" '.summary.pass == 1 and .rows[0].status == "PASS"' "MP-99 authorized sandbox envelope pass"

"$FRAMEWORK" --json all "$TMP/repo/bin/good-cli.sh" >"$TMP/all-good.json" || true
assert_jq "$TMP/all-good.json" '.rows | length == 30' "all mode runs thirty validators"
assert_jq "$TMP/all-good.json" '.summary.applicable >= 2' "all mode records applicable checks"

set +e
"$FRAMEWORK" --json MP-100 "$TMP/repo" >"$TMP/missing.json"
rc=$?
set -e
[[ "$rc" -eq 1 ]] && pass "missing validator exits fail" || fail "missing validator exits fail rc=$rc"

printf 'SUMMARY pass=%s fail=%s\n' "$pass_count" "$fail_count"
[[ "$fail_count" -eq 0 ]]
