#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
RENDER="$ROOT/render.sh"
POLISH_ROOT="$ROOT/polish-gate"

pass_count=0

fail() {
  printf 'FAIL %s\n' "$1" >&2
  exit 1
}

pass() {
  printf 'PASS %s\n' "$1"
  pass_count=$((pass_count + 1))
}

need() {
  command -v "$1" >/dev/null 2>&1 || fail "missing command: $1"
}

find_bash4() {
  local candidate version
  for candidate in /opt/homebrew/bin/bash /usr/local/bin/bash bash; do
    command -v "$candidate" >/dev/null 2>&1 || continue
    version="$("$candidate" -c 'printf "%s\n" "${BASH_VERSINFO[0]}"' 2>/dev/null || true)"
    [[ "$version" -ge 4 ]] 2>/dev/null && { printf '%s\n' "$candidate"; return 0; }
  done
  return 1
}

assert_file() {
  [[ -f "$1" ]] || fail "missing file: $1"
}

assert_executable() {
  [[ -x "$1" ]] || fail "not executable: $1"
}

assert_grep() {
  local pattern="$1" file="$2" label="$3"
  grep -q -- "$pattern" "$file" || fail "$label"
}

assert_jq() {
  local file="$1" filter="$2" label="$3"
  jq -e "$filter" "$file" >/dev/null || {
    jq . "$file" >&2 || true
    fail "$label"
  }
}

validate_json_schema() {
  python3 -c '
import json
import sys
from jsonschema import Draft202012Validator

schema_path, instance_path = sys.argv[1], sys.argv[2]
with open(schema_path, encoding="utf-8") as handle:
    schema = json.load(handle)
with open(instance_path, encoding="utf-8") as handle:
    instance = json.load(handle)
Draft202012Validator.check_schema(schema)
Draft202012Validator(schema, format_checker=Draft202012Validator.FORMAT_CHECKER).validate(instance)
' "$1" "$2" || fail "$3"
}

expect_json_schema_invalid() {
  python3 -c '
import json
import sys
import jsonschema
from jsonschema import Draft202012Validator

schema_path, instance_path = sys.argv[1], sys.argv[2]
with open(schema_path, encoding="utf-8") as handle:
    schema = json.load(handle)
with open(instance_path, encoding="utf-8") as handle:
    instance = json.load(handle)
try:
    Draft202012Validator(schema).validate(instance)
except jsonschema.ValidationError:
    raise SystemExit(0)
raise SystemExit("expected invalid fixture to fail schema validation")
' "$1" "$2" || fail "$3"
}

write_substitutions() {
  local path="$1" repo="$2" now="2026-05-05T00:00:00Z"
  {
    printf 'schema_version=1\n'
    printf 'status=locked\n'
    printf 'repo=%s\n' "$repo"
    printf 'repo_realpath=%s\n' "$repo"
    printf 'git_root=%s\n' "$repo"
    printf 'repo_name=polish-gate-integration-fixture\n'
    printf 'installed_from=%s\n' "$ROOT"
    printf 'template_hash=synthetic-polish-gate-integration-template-hash\n'
    printf 'rendered_at=%s\n' "$now"
    printf 'rendered_by=test_polish_gate_integration.sh\n'
    printf 'lock_hash=synthetic-polish-gate-integration-lock-hash\n'
    printf 'locked_at=%s\n' "$now"
    printf 'locked_by=test_polish_gate_integration.sh\n'
    printf 'source_path=/tmp/polish-gate-integration-source.md\n'
    printf 'source_sha256=synthetic-source-sha256\n'
    printf 'source_section=phase2-p2-06\n'
    printf 'provenance_note=polish gate integration render fixture\n'
    printf 'why_now=Lock full polish-gate template substrate before strict enforcement.\n'
    printf 'mission_source=Phase 2 P2-06 integration fixture.\n'
    printf 'mission_anchor=Template-backed polish-gate install substrate.\n'
    printf 'success_metrics=Render, discovery, scope fixtures, and bad fixture detection all pass.\n'
    printf 'client_stakeholders=Flywheel maintainers and worker panes.\n'
    printf 'frontend_stack=None.\n'
    printf 'backend_stack=Shell, Python, JSON Schema, and flywheel-loop templates.\n'
    printf 'middleware_requirements=None.\n'
    printf 'auth_model=None.\n'
    printf 'data_model_governance=Repo-local .flywheel substrate only.\n'
    printf 'infrastructure_deployment=Temp repo fixture generated by integration test.\n'
    printf 'flywheel_loop_policy=Run polish-gate template tests before strict mode rollout.\n'
    printf 'doctrine_compliance=Use socraticode survey and template fixtures before edits.\n'
    printf 'stakeholder_escalation_map=Owner review before expanding root-domain scope.\n'
    printf 'north_star_outcome=Fresh installs receive a complete polish-gate substrate.\n'
    printf 'primary_beneficiary=Agents executing portable flywheel loop ticks.\n'
    printf 'explicit_non_goals=No production source mutation in this fixture.\n'
    printf 'safety_privacy_boundaries=Fail closed around domain code and client artifacts.\n'
    printf 'mission_change_evidence=Template schema or fixture validation failure.\n'
    printf 'owner_review_cadence=Review before changing polish-gate modes.\n'
    printf 'current_goal=Validate full polish-gate install substrate.\n'
    printf 'measured_acceptance_criteria=Seven integration cases pass.\n'
    printf 'validation_commands=bash templates/flywheel-install/tests/test_polish_gate_integration.sh\n'
    printf 'current_blockers=\n'
    printf 'safe_next_action=Run the rendered discovery script against the temp repo.\n'
    printf 'out_of_scope=Changing render.sh or polish-gate production behavior.\n'
    printf 'success_definition=Rendered substrate validates and discovers only flywheel-local surfaces.\n'
    printf 'resume_context=Continue from P2-06 integration fixture.\n'
    printf 'active_work_in_flight=flywheel-1oruh P2-06 template integration test.\n'
    printf 'confirmed_failure_modes=Malformed fixture detection must fail closed.\n'
    printf 'current_decisions=Repo-local flywheel scope remains the fresh-install default.\n'
    printf 'next_actions=Run cross-test invariant after integration assertions.\n'
    printf 'key_files=templates/flywheel-install/polish-gate\n'
    printf 'lock_receipt=Locked by synthetic P2-06 integration fixture.\n'
    printf 'doctor_strict_command=flywheel-loop doctor --strict --repo . --json\n'
    printf 'source_mutation_allowed_when=Only after strict doctor returns ok and a bounded patch is selected.\n'
  } >"$path"
}

render_template() {
  "$BASH4" "$RENDER" "$@"
}

render_install_fixture() {
  local repo="$1" subs="$2" template out
  mkdir -p "$repo/.flywheel"
  write_substitutions "$subs" "$repo"
  for template in MISSION.md.tmpl GOAL.md.tmpl STATE.md.tmpl loop.json.tmpl; do
    out="$repo/.flywheel/${template%.tmpl}"
    [[ "$template" == "loop.json.tmpl" ]] && out="$repo/.flywheel/loop.json"
    render_template "$ROOT/$template" <"$subs" >"$out"
    ! grep -q '{{[^}][^}]*}}' "$out" || fail "unsubstituted marker in $out"
  done
  cp -R "$POLISH_ROOT" "$repo/.flywheel/"
  find "$repo/.flywheel/polish-gate" -type d -name __pycache__ -prune -exec rm -rf {} +
  cp "$repo/.flywheel/polish-gate/fixtures/bootstrap-mode.json" "$repo/.flywheel/polish-gate/manifest.json"
  chmod +x "$repo/.flywheel/polish-gate/discover-surfaces.py" "$repo/.flywheel/polish-gate/discover-surfaces.sh"
}

seed_domain_fixture() {
  local repo="$1"
  mkdir -p \
    "$repo/.flywheel/scripts" \
    "$repo/.flywheel/wire-or-explain-ledger" \
    "$repo/src/insurance-policies" \
    "$repo/scripts" \
    "$repo/docs/domain"
  printf '#!/usr/bin/env bash\nexit 0\n' >"$repo/.flywheel/scripts/status-doctor.sh"
  printf '#!/usr/bin/env python3\nprint("ledger")\n' >"$repo/.flywheel/wire-or-explain-ledger/writer.py"
  printf '# Flywheel operator docs\n' >"$repo/.flywheel/README.md"
  printf 'class Policy: pass\n' >"$repo/src/insurance-policies/policy_model.py"
  printf '#!/usr/bin/env python3\nprint("domain fetch")\n' >"$repo/scripts/fetch_run_log.py"
  printf '# Domain docs\n' >"$repo/docs/domain/product.md"
  printf '# Root doctrine is domain-owned in this fixture\n' >"$repo/AGENTS.md"
  chmod +x "$repo/.flywheel/scripts/status-doctor.sh" "$repo/.flywheel/wire-or-explain-ledger/writer.py"
}

validate_scope_allowlist_consumption() {
  python3 -c '
import fnmatch
import json
import sys
from pathlib import Path

import jsonschema
from jsonschema import Draft202012Validator

scope_schema_path, fixture_dir_arg, discovery_path, template_schema_path = sys.argv[1:5]
fixture_dir = Path(fixture_dir_arg)
with open(scope_schema_path, encoding="utf-8") as handle:
    scope_schema = json.load(handle)
validator = Draft202012Validator(scope_schema)

with open(template_schema_path, encoding="utf-8") as handle:
    template_schema = json.load(handle)
declared = template_schema["properties"]["polish_gate"]["properties"]["scope_allowlist_profile"]["properties"]["profiles"]["const"]
actual = []
profiles = {}
for path in sorted(fixture_dir.glob("*.json")):
    if path.name == "malformed-no-allowlist.json":
        continue
    with path.open(encoding="utf-8") as handle:
        payload = json.load(handle)
    validator.validate(payload)
    profiles[payload["profile_name"]] = payload
    actual.append(payload["profile_name"])
    if payload["profile_name"] != path.stem:
        raise AssertionError(f"profile_name mismatch for {path}")
if set(actual) != set(declared):
    raise AssertionError(f"declared profiles {declared} != fixtures {actual}")

with (fixture_dir / "malformed-no-allowlist.json").open(encoding="utf-8") as handle:
    malformed = json.load(handle)
try:
    validator.validate(malformed)
except jsonschema.ValidationError:
    pass
else:
    raise AssertionError("malformed-no-allowlist.json validated")

def matches(pattern, rel):
    if pattern == "**/*":
        return True
    if pattern.endswith("/"):
        return rel == pattern[:-1] or rel.startswith(pattern)
    if pattern.endswith("/**"):
        prefix = pattern[:-3]
        return rel == prefix or rel.startswith(prefix + "/")
    return fnmatch.fnmatchcase(rel, pattern)

def allowed(profile, rel):
    if any(matches(pattern, rel) for pattern in profile["blocklist_paths"]):
        return False
    return any(matches(pattern, rel) for pattern in profile["allowlist_paths"])

with open(discovery_path, encoding="utf-8") as handle:
    discovery = json.load(handle)
default_profile = profiles["default"]
for surface in discovery["surfaces"]:
    rel = surface["path"]
    if not allowed(default_profile, rel):
        raise AssertionError(f"default profile did not allow discovered surface {rel}")
excluded = {row["path"] for row in discovery["scope_excluded"]}
for rel in ["src/insurance-policies/policy_model.py", "scripts/fetch_run_log.py", "docs/domain/product.md"]:
    if rel not in excluded:
        raise AssertionError(f"domain fixture was not scope-excluded: {rel}")
    if allowed(default_profile, rel):
        raise AssertionError(f"default profile allowed excluded domain path {rel}")
' "$1" "$2" "$3" "$4" || fail "scope allowlist fixtures were not consumed against discovery output"
}

need cp
need find
need grep
need jq
need python3
[[ -x "$RENDER" ]] || fail "render.sh is not executable"
[[ -d "$POLISH_ROOT" ]] || fail "polish-gate template directory missing"
BASH4="$(find_bash4)" || fail "render.sh requires bash >=4"

tmp="$(mktemp -d "${TMPDIR:-/tmp}/polish-gate-integration.XXXXXX")"
trap 'rm -rf "$tmp"' EXIT
repo="$tmp/rendered-repo"
subs="$tmp/substitutions.env"
discovery_out="$tmp/discovery.json"

mkdir -p "$repo"
git -C "$repo" init -q
render_install_fixture "$repo" "$subs"
seed_domain_fixture "$repo"

assert_file "$repo/.flywheel/MISSION.md"
assert_file "$repo/.flywheel/STATE.md"
assert_file "$repo/.flywheel/loop.json"
assert_file "$repo/.flywheel/polish-gate/README.md"
assert_file "$repo/.flywheel/polish-gate/v1/manifest.schema.json"
assert_file "$repo/.flywheel/polish-gate/v1/discovery-output.schema.json"
assert_file "$repo/.flywheel/polish-gate/v1/scope-allowlist.schema.json"
assert_file "$repo/.flywheel/polish-gate/fixtures/bootstrap-mode.json"
assert_file "$repo/.flywheel/polish-gate/fixtures/audit-only-mode.json"
assert_file "$repo/.flywheel/polish-gate/fixtures/blocking-mode.json"
assert_file "$repo/.flywheel/polish-gate/fixtures/scope-allowlist/alps.json"
assert_file "$repo/.flywheel/polish-gate/fixtures/scope-allowlist/default.json"
assert_file "$repo/.flywheel/polish-gate/fixtures/scope-allowlist/malformed-no-allowlist.json"
assert_executable "$repo/.flywheel/polish-gate/discover-surfaces.py"
assert_executable "$repo/.flywheel/polish-gate/discover-surfaces.sh"
assert_grep '^polish_gate_mode: bootstrap$' "$repo/.flywheel/MISSION.md" "MISSION did not render bootstrap polish gate mode"
assert_grep '^polish_gate_latest_summary: .flywheel/polish-gate/latest.json$' "$repo/.flywheel/MISSION.md" "MISSION did not render latest summary path"
assert_grep '^polish_gate_mode_active: <inherited from mission unless overridden>$' "$repo/.flywheel/STATE.md" "STATE did not render inherited polish gate mode"
assert_jq "$repo/.flywheel/loop.json" '.polish_gate.mode == "bootstrap" and .polish_gate.scope == "repo_local_flywheel"' "loop.json did not render polish_gate defaults"
pass fresh_install_manifest_render

jq '.polish_gate' "$repo/.flywheel/loop.json" >"$tmp/loop-polish-gate.json"
validate_json_schema \
  "$repo/.flywheel/polish-gate/v1/manifest.schema.json" \
  "$tmp/loop-polish-gate.json" \
  "rendered loop polish_gate object does not validate against manifest schema"
pass rendered_loop_manifest_validates

python3 "$repo/.flywheel/polish-gate/discover-surfaces.py" \
  --repo "$repo" \
  --manifest "$repo/.flywheel/polish-gate/manifest.json" \
  --json >"$discovery_out"
validate_json_schema \
  "$repo/.flywheel/polish-gate/v1/discovery-output.schema.json" \
  "$discovery_out" \
  "discovery output did not validate"
assert_jq "$discovery_out" '.surfaces[] | select(.path == ".flywheel/MISSION.md" and .category == "doctrine-doc")' "MISSION not discovered"
assert_jq "$discovery_out" '.surfaces[] | select(.path == ".flywheel/STATE.md" and .category == "doctrine-doc")' "STATE not discovered"
assert_jq "$discovery_out" '.surfaces[] | select(.path == ".flywheel/polish-gate/discover-surfaces.py" and .category == "cli-script")' "discovery script not discovered"
assert_jq "$discovery_out" '.surfaces[] | select(.path == ".flywheel/polish-gate/v1/manifest.schema.json" and .category == "schema")' "manifest schema not discovered"
assert_jq "$discovery_out" '.surfaces[] | select(.path == ".flywheel/polish-gate/fixtures/bootstrap-mode.json" and .category == "test-fixture")' "bootstrap fixture not discovered"
assert_jq "$discovery_out" '.surfaces[] | select(.path == ".flywheel/scripts/status-doctor.sh" and .category == "cli-script")' "repo-local script not discovered"
assert_jq "$discovery_out" '.scope_excluded[] | select(.path == "src/insurance-policies/policy_model.py" and .reason == "root-domain-not-substrate")' "domain source not excluded"
assert_jq "$discovery_out" '.scope_excluded[] | select(.path == "scripts/fetch_run_log.py" and .reason == "root-domain-not-substrate")' "domain script not excluded"
pass discovery_walks_render_output

missing_mode="$tmp/missing-mode.json"
bad_scope="$tmp/bad-scope.json"
jq 'del(.mode)' "$repo/.flywheel/polish-gate/fixtures/bootstrap-mode.json" >"$missing_mode"
jq '.scope = "unsupported_scope"' "$repo/.flywheel/polish-gate/fixtures/bootstrap-mode.json" >"$bad_scope"
expect_json_schema_invalid \
  "$repo/.flywheel/polish-gate/v1/manifest.schema.json" \
  "$missing_mode" \
  "manifest schema accepted fixture missing mode"
expect_json_schema_invalid \
  "$repo/.flywheel/polish-gate/v1/manifest.schema.json" \
  "$bad_scope" \
  "manifest schema accepted unsupported scope"
set +e
python3 "$repo/.flywheel/polish-gate/discover-surfaces.py" \
  --repo "$repo" \
  --manifest "$bad_scope" \
  --json >"$tmp/bad-scope-discovery.json" 2>"$tmp/bad-scope-discovery.err"
bad_discovery_rc=$?
set -e
[[ "$bad_discovery_rc" -ne 0 ]] || fail "discovery accepted unsupported scope fixture"
grep -q 'unsupported manifest scope: unsupported_scope' "$tmp/bad-scope-discovery.err" \
  || fail "discovery did not report unsupported scope malformation"
pass bad_fixture_detection_roundtrip

validate_scope_allowlist_consumption \
  "$repo/.flywheel/polish-gate/v1/scope-allowlist.schema.json" \
  "$repo/.flywheel/polish-gate/fixtures/scope-allowlist" \
  "$discovery_out" \
  "$ROOT/schema.json"
pass scope_allowlist_consumption

mission_mode="$(awk -F': *' '$1 == "polish_gate_mode" { print $2; exit }' "$repo/.flywheel/MISSION.md")"
state_raw="$(awk -F': *' '$1 == "polish_gate_mode_active" { print $2; exit }' "$repo/.flywheel/STATE.md")"
state_effective="$state_raw"
[[ "$state_raw" == "<inherited from mission unless overridden>" ]] && state_effective="$mission_mode"
loop_mode="$(jq -r '.polish_gate.mode' "$repo/.flywheel/loop.json")"
[[ "$mission_mode" == "bootstrap" ]] || fail "MISSION polish gate mode is not bootstrap"
[[ "$state_effective" == "$mission_mode" ]] || fail "STATE effective polish gate mode did not inherit MISSION mode"
[[ "$loop_mode" == "$mission_mode" ]] || fail "loop.json polish gate mode did not match MISSION mode"
pass polish_gate_mode_cross_consistency

bash "$ROOT/tests/test_render.sh" >/dev/null
bash "$ROOT/tests/test_polish_gate_schemas.sh" >/dev/null
bash "$ROOT/tests/test_polish_gate_discovery.sh" >/dev/null
bash "$ROOT/tests/test_polish_gate_scope_allowlist.sh" >/dev/null
pass cross_test_invariant_prior_tests

[[ "$pass_count" -eq 7 ]] || fail "expected 7 integration cases, observed $pass_count"
printf 'SUMMARY pass=%d fail=0\n' "$pass_count"
