#!/usr/bin/env bash
# cross-time-synthesis-probe.sh — smallest recurring measurement
# for value-gap dimension `cross-time-synthesis` (#8 of 10 in
# `.flywheel/scripts/value-gap-probe.sh:DIMENSIONS[]`).
#
# Owns: bead flywheel-1rmp.9 (closed 2026-05-09). Duplicate-of-.9:
# bead flywheel-1rmp.19 (auto-generated by value-gap-probe.sh dimension
# rotation when .9 was already in flight; closed 2026-05-09 against this
# same probe path with no functional change). Sisters: flywheel-1rmp.5
# (cost-telemetry-token-burn) and flywheel-1rmp.7
# (mobile-eats-end-user-health) — same shape: proxy metrics +
# explicit no-surface receipt.
#
# What this measures (proxy from the last N=10 handoff files):
#   - handoffs_observed                (raw count)
#   - with_tomorrow_you_section        (matches "Open question|Tomorrow|Next session|Pending|Unresolved" header)
#   - without_tomorrow_you_section
#   - tomorrow_you_coverage_ratio      (with / observed)
#   - latest_handoff_age_hours         (mtime delta of newest)
#   - tomorrow_you_artifact_today      ("present" iff today wrote a handoff
#                                         carrying a tomorrow-you section,
#                                         else "missing")
#
# Step 4o anti-pattern guardrail: SURFACES the gap; does NOT
# auto-create beads, dispatch fixes, or auto-write tomorrow-you
# artifacts. Operators / orchestrators write handoffs through
# `/flywheel:handoff` and similar surfaces.
#
# Stable exit codes: 0 ok | 1 domain | 64 usage
# Triad: doctor / info / schema; --json default for robot consumers.

set -uo pipefail

VERSION="cross-time-synthesis-probe.v1"
SCRIPT_VERSION="2026-05-09.1"

REPO="${CROSS_TIME_REPO:-/Users/josh/Developer/flywheel}"
HANDOFF_DIR="${CROSS_TIME_HANDOFF_DIR:-$REPO/.flywheel/handoffs}"
LEDGER="${CROSS_TIME_LEDGER:-$HOME/.local/state/flywheel/cross-time-synthesis.jsonl}"
SAMPLE_N="${CROSS_TIME_SAMPLE_N:-10}"
TOMORROW_HEADER_RE='^## (Open question|Open Questions?|Tomorrow|Tomorrow-?[Yy]ou|Next session|Pending|Unresolved|Carryover|Handoff Questions?)'

JSON_OUT=0
MODE="run"
APPLY=0
DRY_RUN=0

usage() {
  cat <<'USAGE'
Usage:
  cross-time-synthesis-probe.sh [--apply|--dry-run] [--sample N] [--json]
  cross-time-synthesis-probe.sh --doctor [--json]
  cross-time-synthesis-probe.sh --info [--json]
  cross-time-synthesis-probe.sh --schema [--json]
  cross-time-synthesis-probe.sh --help

Smallest recurring measurement for the value-gap-hunter dimension
"cross-time-synthesis" (Meadows #8 information flow). Probes the
last N handoffs for tomorrow-you section coverage; emits proxy
metrics + presence signal for today's tomorrow-you artifact.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --json) JSON_OUT=1; shift ;;
    --apply) APPLY=1; DRY_RUN=0; shift ;;
    --dry-run) DRY_RUN=1; APPLY=0; shift ;;
    --sample) SAMPLE_N="${2:?}"; shift 2 ;;
    --handoff-dir) HANDOFF_DIR="${2:?}"; shift 2 ;;
    --ledger) LEDGER="${2:?}"; shift 2 ;;
    --doctor) MODE="doctor"; shift ;;
    --info) MODE="info"; shift ;;
    --schema) MODE="schema"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "cross-time-synthesis-probe.sh: unknown arg: $1" >&2; usage >&2; exit 64 ;;
  esac
done

if [[ $MODE == "run" && $APPLY -eq 0 && $DRY_RUN -eq 0 ]]; then
  DRY_RUN=1
fi

now_iso() { date -u +%Y-%m-%dT%H:%M:%SZ; }
today_utc() { date -u +%Y-%m-%d; }
emit() {
  if [[ $JSON_OUT -eq 1 || $MODE == "info" || $MODE == "schema" || $MODE == "doctor" ]]; then
    printf '%s\n' "$1"
  fi
}

info_payload() {
  jq -nc \
    --arg version "$VERSION" \
    --arg script_version "$SCRIPT_VERSION" \
    --arg repo "$REPO" \
    --arg handoff_dir "$HANDOFF_DIR" \
    --arg ledger "$LEDGER" \
    --argjson sample_n "$SAMPLE_N" \
    --arg header_re "$TOMORROW_HEADER_RE" \
    '{
      version: $version,
      script_version: $script_version,
      schema_version: "cross-time-synthesis/v1",
      mode: "info",
      repo: $repo,
      handoff_dir: $handoff_dir,
      ledger: $ledger,
      sample_n_default: $sample_n,
      tomorrow_header_regex: $header_re,
      modes: ["run","doctor","info","schema"],
      owns: "flywheel-1rmp.9",
      duplicate_of_owns: ["flywheel-1rmp.19"],
      parent: "flywheel-1rmp",
      value_gap_dimension: "cross-time-synthesis",
      meadows_tier: "#8 information flow",
      step_4o_anti_pattern_guardrail: "this probe surfaces; it does NOT auto-create handoffs or dispatch fixes",
      handoff_authoring_surface: "/flywheel:handoff (operator-driven)",
      status: "ok"
    }'
}

schema_payload() {
  jq -nc '{
    schema_version: "cross-time-synthesis/v1",
    ledger_row_required_fields: [
      "schema_version","ts","handoff_dir","sample_n",
      "handoffs_observed","with_tomorrow_you_section",
      "without_tomorrow_you_section","tomorrow_you_coverage_ratio",
      "latest_handoff_age_hours","tomorrow_you_artifact_today",
      "tomorrow_you_artifact_today_reason","handoffs"
    ],
    proxy_metrics: [
      {"name":"handoffs_observed","describes":"count of handoff *.md files in the sample window"},
      {"name":"with_tomorrow_you_section","describes":"handoffs whose body matches the tomorrow_header_regex"},
      {"name":"tomorrow_you_coverage_ratio","describes":"with / observed (0..1)"},
      {"name":"latest_handoff_age_hours","describes":"hours since newest handoff mtime"},
      {"name":"tomorrow_you_artifact_today","describes":"present|missing — whether any handoff written today has a tomorrow-you section"}
    ],
    tomorrow_you_artifact_today_enum: ["present","missing","unknown"],
    surfaced_via: ["ledger:~/.local/state/flywheel/cross-time-synthesis.jsonl","cli:cross-time-synthesis-probe.sh","value-gap-probe parent ledger"],
    exit_codes: {"0":"ok","1":"domain","64":"usage"},
    mode: "schema",
    status: "ok"
  }'
}

doctor_payload() {
  local issues=()
  command -v jq >/dev/null 2>&1 || issues+=("jq_missing")
  [[ -d "$HANDOFF_DIR" ]] || issues+=("handoff_dir_missing=$HANDOFF_DIR")
  mkdir -p "$(dirname "$LEDGER")" 2>/dev/null
  [[ -w "$(dirname "$LEDGER")" ]] || issues+=("ledger_dir_not_writable=$(dirname "$LEDGER")")
  local issues_json
  if [[ ${#issues[@]} -gt 0 ]]; then
    issues_json=$(printf '%s\n' "${issues[@]}" | jq -R . | jq -s .)
  else
    issues_json='[]'
  fi
  jq -nc \
    --arg version "$VERSION" \
    --argjson issues "$issues_json" \
    '{
      version: $version,
      schema_version: "cross-time-synthesis/v1",
      mode: "doctor",
      issues: $issues,
      status: (if ($issues|length)==0 then "ok" else "degraded" end)
    }'
}

# --- core measurement ---------------------------------------------------------
mtime_iso() {
  local p="$1"
  if [[ -f "$p" ]]; then
    stat -f '%Sm' -t '%Y-%m-%dT%H:%M:%SZ' "$p" 2>/dev/null
  fi
}

mtime_epoch() {
  local p="$1"
  if [[ -f "$p" ]]; then
    stat -f '%m' "$p" 2>/dev/null
  fi
}

run_pass() {
  local mode_label="$1"
  local now_epoch today
  now_epoch=$(date -u +%s)
  today=$(today_utc)

  if [[ ! -d "$HANDOFF_DIR" ]]; then
    emit "$(jq -nc \
      --arg dir "$HANDOFF_DIR" \
      '{status:"fail",error:"handoff_dir_missing",handoff_dir:$dir}')"
    return 1
  fi

  local handoffs_json='[]'
  local observed=0 with=0 newest_epoch=0 has_today_with=false
  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    observed=$((observed+1))
    local has_section=false
    if grep -qE "$TOMORROW_HEADER_RE" "$f" 2>/dev/null; then
      has_section=true
      with=$((with+1))
    fi
    local mt_iso mt_ep
    mt_iso=$(mtime_iso "$f")
    mt_ep=$(mtime_epoch "$f")
    if [[ -n "$mt_ep" ]] && (( mt_ep > newest_epoch )); then
      newest_epoch=$mt_ep
    fi
    if [[ "$has_section" == "true" && "$mt_iso" == "$today"* ]]; then
      has_today_with=true
    fi
    handoffs_json=$(jq -c \
      --arg name "$(basename "$f")" \
      --arg mt "$mt_iso" \
      --arg has "$has_section" \
      '. + [{file: $name, mtime: $mt, has_tomorrow_you_section: ($has == "true")}]' \
      <<<"$handoffs_json")
  done < <(ls -t "$HANDOFF_DIR"/*.md 2>/dev/null | head -n "$SAMPLE_N")

  local without=$((observed - with))
  local coverage='0'
  if (( observed > 0 )); then
    coverage=$(python3 -c "print(round($with / $observed, 4))" 2>/dev/null || echo "0")
  fi
  local age_hours=999999
  if (( newest_epoch > 0 )); then
    age_hours=$(( (now_epoch - newest_epoch) / 3600 ))
  fi
  local today_status="missing"
  local today_reason="no handoff written today $today contains a tomorrow-you section"
  if [[ "$has_today_with" == "true" ]]; then
    today_status="present"
    today_reason="today $today already has a handoff with a tomorrow-you section"
  fi

  local row
  row=$(jq -nc \
    --arg ts "$(now_iso)" \
    --arg dir "$HANDOFF_DIR" \
    --argjson sample_n "$SAMPLE_N" \
    --argjson observed "$observed" \
    --argjson with "$with" \
    --argjson without "$without" \
    --arg coverage "$coverage" \
    --argjson age_hours "$age_hours" \
    --arg today_status "$today_status" \
    --arg today_reason "$today_reason" \
    --argjson handoffs "$handoffs_json" \
    '{
      schema_version: "cross-time-synthesis/v1",
      ts: $ts,
      handoff_dir: $dir,
      sample_n: $sample_n,
      handoffs_observed: $observed,
      with_tomorrow_you_section: $with,
      without_tomorrow_you_section: $without,
      tomorrow_you_coverage_ratio: ($coverage | tonumber? // 0),
      latest_handoff_age_hours: $age_hours,
      tomorrow_you_artifact_today: $today_status,
      tomorrow_you_artifact_today_reason: $today_reason,
      handoffs: $handoffs
    }')

  if [[ "$mode_label" == "apply" ]]; then
    mkdir -p "$(dirname "$LEDGER")" 2>/dev/null
    printf '%s\n' "$row" >> "$LEDGER" 2>/dev/null
  fi

  emit "$(printf '%s' "$row" | jq -c \
    --arg mode "$mode_label" --arg ledger "$LEDGER" \
    '{mode:$mode, ledger:$ledger} + .')"
  return 0
}

case "$MODE" in
  info)   emit "$(info_payload)"; exit 0 ;;
  schema) emit "$(schema_payload)"; exit 0 ;;
  doctor)
    payload="$(doctor_payload)"
    emit "$payload"
    [[ "$(printf '%s' "$payload" | jq -r .status)" == "ok" ]] && exit 0 || exit 1
    ;;
esac

if [[ $DRY_RUN -eq 1 ]]; then
  run_pass dry-run
  exit $?
fi
run_pass apply
exit $?
