#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"
LIB="$ROOT/.flywheel/scripts/fleet-coherence-lib.sh"
# shellcheck source=.flywheel/scripts/fleet-coherence-lib.sh
source "$LIB"
SCANNER="fleet-coherence-scanner/v1"
MODE=scan; JSON=0; STATE_DIR=""; TOPOLOGY="$HOME/.local/state/flywheel/session-topology.jsonl"; ROSTER="$HOME/.local/state/flywheel/fleet-roster.json"; PANE_WORK="$HOME/.local/state/flywheel/pane-work-signal.jsonl"; NTM="${NTM_BIN:-$HOME/.local/bin/ntm}"; HEALTH_TIMEOUT=3; PANE_TIMEOUT=3; TOTAL_TIMEOUT=30; LOCK_TIMEOUT=2
usage(){ echo 'fleet-coherence-scan.sh --once [--json] [--state-dir PATH] [--ntm-bin PATH]'; }
while [[ $# -gt 0 ]]; do case "$1" in --once) MODE=scan; shift;; --json) JSON=1; shift;; --info) MODE=info; shift;; --schema) MODE=schema; shift;; --state-dir) STATE_DIR="${2:?}"; shift 2;; --topology-file) TOPOLOGY="${2:?}"; shift 2;; --roster-file) ROSTER="${2:?}"; shift 2;; --pane-work-signal-file|--pane-work-signal) PANE_WORK="${2:?}"; shift 2;; --ntm-bin) NTM="${2:?}"; shift 2;; --health-timeout-sec) HEALTH_TIMEOUT="${2:?}"; shift 2;; --pane-timeout-sec) PANE_TIMEOUT="${2:?}"; shift 2;; --total-timeout-sec) TOTAL_TIMEOUT="${2:?}"; shift 2;; --lock-timeout-sec) LOCK_TIMEOUT="${2:?}"; shift 2;; -h|--help) usage; exit 0;; *) echo "unknown option: $1" >&2; exit 64;; esac; done
fc_require_jq || exit 127
[[ -n "$STATE_DIR" ]] && export FLYWHEEL_FLEET_COHERENCE_STATE_DIR="$STATE_DIR"
EVENTS="$(fc_events_path)"; LATEST="$(fc_latest_path)"; STATE_DIR="$(fc_state_dir)"; LOCK="$STATE_DIR/fleet-coherence-scan.lock"
emit(){ [[ "$JSON" == 1 ]] && jq -cS . || jq .; }
info(){ jq -ncS --arg sc "$SCANNER" '{schema_version:"fleet-coherence-scanner-info/v1",status:"ok",scanner_contract:$sc,writes_via:"fleet-coherence-lib.sh fc_append_event",p95_targets_sec:{sessions_8:10,sessions_16:60},native_surface:["ntm list/sessions --json","ntm activity --json","ntm health --json"],classifier_pack:"fleet-coherence-classifiers/v1 shadow"}'; }
schema(){ jq -ncS --arg sc "$SCANNER" '{schema_version:"fleet-coherence-scanner/schema/v1",emitted_event:{class:"fleet_scan_heartbeat",detector_version:$sc},required_sources:["ntm sessions/list --json","ntm activity <session> --json","ntm health <session> --json"],drift_classification:"out_of_scope_phase_1a"}'; }
run_timeout(){ python3 - "$1" "$2" "$3" "${@:4}" <<'PY'
import subprocess,sys
sec=float(sys.argv[1]); out=sys.argv[2]; err=sys.argv[3]; cmd=sys.argv[4:]
try:
 r=subprocess.run(cmd,text=True,capture_output=True,timeout=sec)
 open(out,'w').write(r.stdout); open(err,'w').write(r.stderr); sys.exit(r.returncode)
except subprocess.TimeoutExpired as e:
 open(out,'w').write(e.stdout or ''); open(err,'w').write((e.stderr or '')+f'\ncommand timed out after {sec}s\n'); sys.exit(124)
PY
}
read_topology(){ [[ -f "$TOPOLOGY" ]] || { jq -ncS --arg p "$TOPOLOGY" '{status:"missing",path:$p,row_count:0,session_count:0,expected_pane_total:0,latest_rows:[]}'; return; }; jq -s -cS --arg p "$TOPOLOGY" '[.[]|select(type=="object")] as $r|{status:"ok",path:$p,row_count:($r|length),session_count:([ $r[]|.session//empty ]|unique|length),expected_pane_total:([ $r[]|.expected_pane_count//0 ]|add//0),latest_rows:([ $r[]|{session:(.session//"unknown"),pane:(.pane//null),role:(.role//null),expected_pane_count:(.expected_pane_count//null),ts:(.ts//null)}])}' "$TOPOLOGY" 2>/dev/null || jq -ncS --arg p "$TOPOLOGY" '{status:"invalid_json",path:$p,row_count:0,session_count:0,expected_pane_total:0,latest_rows:[]}'; }
read_roster(){ [[ -f "$ROSTER" ]] || { jq -ncS --arg p "$ROSTER" '{status:"missing",path:$p,entry_count:0,session_count:0}'; return; }; jq -cS --arg p "$ROSTER" '{status:"ok",path:$p,entry_count:((.members//.agents//.sessions//[])|length),session_count:((.members//.agents//.sessions//[])|map(.session//empty)|unique|length)}' "$ROSTER" 2>/dev/null || jq -ncS --arg p "$ROSTER" '{status:"invalid_json",path:$p,entry_count:0,session_count:0}'; }
read_pane_work(){ [[ -f "$PANE_WORK" ]] || { jq -ncS --arg p "$PANE_WORK" --argjson t "$PANE_TIMEOUT" '{status:"missing",path:$p,row_count:0,sampled_rows:0,pane_timeout_sec:$t}'; return; }; jq -s -cS --arg p "$PANE_WORK" --argjson total "$(wc -l <"$PANE_WORK"|tr -d ' ')" --argjson t "$PANE_TIMEOUT" '[.[]|select(type=="object")] as $r|{status:"ok",path:$p,row_count:$total,sampled_rows:($r|length),pane_timeout_sec:$t,session_count:($r|map(.session//empty)|unique|length)}' "$PANE_WORK" 2>/dev/null || jq -ncS --arg p "$PANE_WORK" '{status:"invalid_json",path:$p,row_count:0,sampled_rows:0}'; }
ntm_json(){ local out err rc status sessions health_rows s; out="$(mktemp)"; err="$(mktemp)"; health_rows="$(mktemp)"; : >"$health_rows"; set +e; run_timeout "$HEALTH_TIMEOUT" "$out" "$err" "$NTM" sessions list --json; rc=$?; [[ "$rc" != 0 ]] && run_timeout "$HEALTH_TIMEOUT" "$out" "$err" "$NTM" list --json && rc=$?; set -e; status=ok; [[ "$rc" == 124 ]] && status=timeout; [[ "$rc" != 0 && "$status" != timeout ]] && status=error; jq empty "$out" >/dev/null 2>&1 || [[ "$status" != ok ]] || status=invalid_json; sessions="$(mktemp)"; [[ "$status" == ok ]] && jq -r '(.sessions//[])[]|.name//.session//empty' "$out" >"$sessions" || : >"$sessions"; while IFS= read -r s; do [[ -n "$s" ]] || continue; set +e; run_timeout "$HEALTH_TIMEOUT" "$out" "$err" "$NTM" activity "$s" --json >/dev/null; run_timeout "$HEALTH_TIMEOUT" "$out" "$err" "$NTM" health "$s" --json; rc=$?; set -e; if [[ "$rc" == 124 ]]; then jq -ncS --arg session "$s" '{session:$session,status:"timeout",pane_count:0}' >>"$health_rows"; elif [[ "$rc" != 0 ]]; then jq -ncS --arg session "$s" '{session:$session,status:"error",pane_count:0}' >>"$health_rows"; else jq -cS --arg session "$s" '{session:$session,status:"ok",pane_count:((.panes//.agents//[])|length),reported_status:(.status//null)}' "$out" >>"$health_rows"; fi; done <"$sessions"; jq -s -cS --arg st "$status" --argjson rc "$rc" --argjson sc "$(wc -l <"$sessions"|tr -d ' ')" '{list:{status:$st,command:"ntm sessions list --json fallback ntm list --json",rc:$rc,session_count:$sc},health:{status:(if length==0 then "none" elif any(.status!="ok") then "warn" else "ok" end),session_count:length,ok_count:([.[]|select(.status=="ok")]|length),failed_count:([.[]|select(.status=="error" or .status=="invalid_json")]|length),timeout_count:([.[]|select(.status=="timeout")]|length),pane_total:(([.[]|.pane_count]|add)//0),sessions:.}}' "$health_rows"; }
make_event(){ jq -ncS --arg now "$(fc_now)" --arg sc "$SCANNER" --argjson ev "$1" '{schema_version:2,record_type:"event",class:"fleet_scan_heartbeat",state:"open",severity:(if $ev.status=="ok" then "info" else "warning" end),detector:"fleet-coherence",detector_version:$sc,detector_git_sha:"runtime",event_id:("fleet_scan_heartbeat_"+($now|gsub("[^0-9A-Za-z]";""))),dedupe_key:("fleet_scan_heartbeat:"+$now),session:"fleet-coherence",pane:null,ts:$now,source_ts:$now,first_seen_ts:$now,last_seen_ts:$now,seen_count:1,sample_count:($ev.sources.ntm.health.session_count//0),sample_window_s:0,confidence:0.5,source_age_s:0,suppression_id:null,resend_after_ts:null,evidence:($ev+{phase:"phase_1a_scanner_skeleton",phase_scope:"read fleet substrates and emit neutral heartbeat, no drift classification"}),raw_source_refs:[],actions:{shadow_mode:true,would_l61:false,would_bead:false,would_no_bead_reason:"phase 1a scanner skeleton emits neutral heartbeat only",bead_id:null,no_bead_reason:"phase 1a scanner skeleton emits neutral heartbeat only",receipt_required:false},l61:{ntm_attempted:false,ntm_pane:null,ntm_session:null,ntm_result:null,ntm_sent_at:null,agent_mail_attempted:false,agent_mail_from:null,agent_mail_to:null,agent_mail_message_id:null,agent_mail_sent_at:null,l61_pairing_status:"not_attempted",degraded_reason:null,fleet_mail_identity_source:"not_applicable",project_key:null,vault_token_validated:false},l62:{repair_callback_required:false,sd_count:0,sd_ids:[]},l63:{recovery_action_requires_drill:false,recovery_drill_ids:[]}}'; }
[[ "$MODE" == info ]] && { info|emit; exit; }; [[ "$MODE" == schema ]] && { schema|emit; exit; }
mkdir -p "$STATE_DIR"; if ! mkdir "$LOCK" 2>/dev/null; then jq -ncS --arg sc "$SCANNER" --arg l "$LOCK" '{schema_version:"fleet-coherence-scan-run/v1",status:"skipped_lock",scanner_contract:$sc,l112_observed:"OK_phase1a_scanner",lock_dir:$l,appended:false,reason:"overlap_lock_held"}'|emit; exit; fi
top="$(read_topology)"; roster="$(read_roster)"; pane="$(read_pane_work)"; ntm="$(ntm_json)"; warnings="$(jq -ncS --argjson t "$top" --argjson r "$roster" --argjson p "$pane" --argjson n "$ntm" '[] + (if $t.status=="ok" then [] else ["topology_"+$t.status] end) + (if ($r.status=="ok" or $r.status=="missing") then [] else ["roster_"+$r.status] end) + (if ($p.status=="ok" or $p.status=="missing") then [] else ["pane_work_signal_"+$p.status] end) + (if $n.list.status=="ok" then [] else ["ntm_list_"+$n.list.status] end) + (if ($n.health.failed_count//0)>0 then ["ntm_health_failed"] else [] end) + (if ($n.health.timeout_count//0)>0 then ["ntm_health_timeout"] else [] end)')"; status="$(jq -nr --argjson w "$warnings" 'if ($w|length)==0 then "ok" else "warn" end')"; evidence="$(jq -ncS --arg status "$status" --argjson warnings "$warnings" --argjson topology "$top" --argjson roster "$roster" --argjson pane_work_signal "$pane" --argjson ntm "$ntm" '{status:$status,warnings:$warnings,sources:{topology:$topology,roster:$roster,pane_work_signal:$pane_work_signal,ntm:$ntm}}')"; event="$(make_event "$evidence")"; receipt="$(fc_append_event "$event" "$EVENTS" "$LATEST")"; jq -ncS --arg sc "$SCANNER" --arg status "$status" --arg events "$EVENTS" --arg latest "$LATEST" --argjson warnings "$warnings" --argjson evidence "$evidence" --argjson event "$event" --argjson writer "$receipt" '{schema_version:"fleet-coherence-scan-run/v1",status:$status,scanner_contract:$sc,generated_at:$event.ts,l112_observed:"OK_phase1a_scanner",warnings:$warnings,appended:true,events_path:$events,latest_path:$latest,event_id:$event.event_id,dedupe_key:$event.dedupe_key,evidence:$evidence,write_receipt:$writer}'|emit

# Meta-Learning Cross-References (2026-05-19)
# Batch-16 comment backfill; citations are documentation-only and do not alter runtime behavior.
# Related: `/Users/josh/Developer/skillos/.flywheel/doctrine/meta-learnings/MP-19-flywheel-engagement-protocol.md`
# Related: `/Users/josh/Developer/skillos/.flywheel/doctrine/meta-learnings/MP-61-agent-first-operator-surface.md`
