#!/usr/bin/env bash
# flywheel-cli-surface: true
# canonical-cli-scoping: passing (partial -> passing per bead flywheel-k8gcv.8)
# mobile-eats-end-user-health-probe.sh — smallest recurring measurement
# for value-gap dimension `mobile-eats-end-user-health` (#6 of 10 in
# `.flywheel/scripts/value-gap-probe.sh:DIMENSIONS[]`).
#
# Owns: bead flywheel-1rmp.7 (closed 2026-05-09). Duplicate-of-.7:
# bead flywheel-1rmp.17 (auto-generated by value-gap-probe.sh dimension
# rotation when .7 was already in flight; closed 2026-05-09 against this
# same probe path with no functional change). Sister: flywheel-1rmp.5
# (cost-telemetry-token-burn, closed); same shape: proxy metrics +
# explicit no-surface receipt.
#
# What this measures (proxy-only — production database is not exposed
# via flywheel substrate today):
#   - artifact presence + freshness for the SaaS KPI surface
#     (saas-kpi-strip.ts, saas-metrics.ts, mrr-rollup.ts,
#     community-health-metrics.ts) and their tests
#   - mtime-as-freshness proxy (newest-source-edit per surface)
#   - test coverage proxy (each KPI source has a paired *.test.ts)
#
# Step 4o anti-pattern guardrail: this probe SURFACES the gap; it does
# NOT auto-create beads or dispatch fixes. Parent value-gap-probe.sh
# enforces that contract.
#
# Stable exit codes: 0 ok | 1 domain | 64 usage
# Triad: doctor / info / schema; --json default for robot consumers.

set -euo pipefail

VERSION="mobile-eats-end-user-health-probe.v1.1.0"
SCHEMA_VERSION="mobile-eats-end-user-health/v1"
SCRIPT_VERSION="2026-05-11.1"
IDEMPOTENCY_KEY=""

now_iso() { date -u +%Y-%m-%dT%H:%M:%SZ; }

REPO="${MOBILE_EATS_REPO:-/Users/josh/Developer/mobile-eats}"
LEDGER="${MOBILE_EATS_HEALTH_LEDGER:-$HOME/.local/state/flywheel/mobile-eats-end-user-health.jsonl}"
HOURS_FRESHNESS_BUDGET="${MOBILE_EATS_HEALTH_FRESHNESS_HOURS:-72}"

KPI_SURFACES=(
  "next-app/lib/mobile-eats/saas-kpi-strip.ts"
  "next-app/lib/mobile-eats/saas-metrics.ts"
  "next-app/lib/mobile-eats/mrr-rollup.ts"
  "next-app/lib/mobile-eats/community-health-metrics.ts"
)
KPI_TESTS=(
  "next-app/lib/mobile-eats/saas-kpi-strip.test.ts"
  "next-app/lib/mobile-eats/saas-metrics.test.ts"
  "next-app/lib/mobile-eats/community-health-metrics.test.ts"
)

JSON_OUT=0
MODE="run"
APPLY=0
DRY_RUN=0

usage() {
  cat <<'USAGE'
Usage:
  mobile-eats-end-user-health-probe.sh [--apply --idempotency-key KEY|--dry-run] [--json]
  mobile-eats-end-user-health-probe.sh --doctor [--json]
  mobile-eats-end-user-health-probe.sh --info [--json]
  mobile-eats-end-user-health-probe.sh --schema [--json]
  mobile-eats-end-user-health-probe.sh --examples [--json]
  mobile-eats-end-user-health-probe.sh doctor --json
  mobile-eats-end-user-health-probe.sh health --json
  mobile-eats-end-user-health-probe.sh validate --json
  mobile-eats-end-user-health-probe.sh audit --json [--limit N]
  mobile-eats-end-user-health-probe.sh why [topic] [--json]
  mobile-eats-end-user-health-probe.sh quickstart [--json]
  mobile-eats-end-user-health-probe.sh repair --scope <ledger-prime> [--dry-run|--apply --idempotency-key KEY] [--json]
  mobile-eats-end-user-health-probe.sh --help

Smallest recurring measurement for the value-gap-hunter dimension
"mobile-eats-end-user-health" (Meadows #8 information flow). Probes
artifact presence + mtime freshness for SaaS-tier KPI sources;
emits explicit no-surface receipt for first-party DB-backed user
health telemetry. --apply writes a ledger row and requires
--idempotency-key per canonical apply contract.
USAGE
}

emit_examples_text() {
  cat <<'EOF'
examples:
  mobile-eats-end-user-health-probe.sh --json
  mobile-eats-end-user-health-probe.sh --dry-run --json
  mobile-eats-end-user-health-probe.sh --apply --idempotency-key meu-2026-05-11 --json
  mobile-eats-end-user-health-probe.sh --doctor --json
  mobile-eats-end-user-health-probe.sh doctor --json
  mobile-eats-end-user-health-probe.sh audit --json
EOF
}

emit_examples_json() {
  jq -nc --arg sv "$SCHEMA_VERSION" '{
    schema_version:$sv,
    command:"examples",
    examples:[
      {name:"dry-run-probe",invocation:"mobile-eats-end-user-health-probe.sh --json",purpose:"default dry-run probe; emits KPI surface presence + mtime freshness without writing ledger"},
      {name:"apply-write-ledger",invocation:"mobile-eats-end-user-health-probe.sh --apply --idempotency-key meu-2026-05-11 --json",purpose:"apply mode: append probe row to ledger (requires --idempotency-key)"},
      {name:"doctor-flag",invocation:"mobile-eats-end-user-health-probe.sh --doctor --json",purpose:"doctor mode envelope: jq+repo+ledger writability (legacy flag-style)"},
      {name:"doctor-positional",invocation:"mobile-eats-end-user-health-probe.sh doctor --json",purpose:"canonical doctor subcommand with .checks shape"},
      {name:"audit",invocation:"mobile-eats-end-user-health-probe.sh audit --json",purpose:"tail recent probe ledger rows"}
    ]
  }'
}

emit_canonical_doctor() {
  local ts; ts="$(now_iso)"
  local jq_status="pass"; command -v jq >/dev/null 2>&1 || jq_status="fail"
  local repo_status="pass"; [[ -d "$REPO" ]] || repo_status="fail"
  local ledger_dir; ledger_dir="$(dirname "$LEDGER")"
  local ledger_status="pass"
  mkdir -p "$ledger_dir" 2>/dev/null || true
  if [[ -e "$LEDGER" ]]; then
    [[ -w "$LEDGER" ]] || ledger_status="fail"
  else
    [[ -w "$ledger_dir" ]] || ledger_status="warn"
  fi
  local surfaces_present=0
  local rel
  for rel in "${KPI_SURFACES[@]}"; do
    [[ -f "$REPO/$rel" ]] && surfaces_present=$((surfaces_present + 1))
  done
  local surfaces_total=${#KPI_SURFACES[@]}
  local surfaces_status="pass"
  if [[ "$surfaces_present" -eq 0 ]]; then
    surfaces_status="fail"
  elif [[ "$surfaces_present" -lt "$surfaces_total" ]]; then
    surfaces_status="warn"
  fi
  local overall="pass"
  for s in "$jq_status" "$repo_status" "$ledger_status" "$surfaces_status"; do
    case "$s" in
      fail) overall="fail" ;;
      warn) [[ "$overall" == "pass" ]] && overall="warn" ;;
    esac
  done
  jq -nc --arg sv "$SCHEMA_VERSION.doctor" --arg ts "$ts" --arg overall "$overall" \
    --arg jq_s "$jq_status" --arg repo_s "$repo_status" --arg repo "$REPO" \
    --arg ledger_s "$ledger_status" --arg ledger "$LEDGER" \
    --arg surfaces_s "$surfaces_status" --argjson present "$surfaces_present" --argjson total "$surfaces_total" \
    '{
      schema_version:$sv,
      command:"doctor",
      ts:$ts,
      status:$overall,
      checks:[
        {name:"jq",status:$jq_s,detail:"jq required for envelope emission"},
        {name:"mobile_eats_repo",status:$repo_s,path:$repo,detail:"mobile-eats repo root for KPI source resolution"},
        {name:"ledger_writable",status:$ledger_s,path:$ledger,detail:"append-only probe ledger"},
        {name:"kpi_surfaces",status:$surfaces_s,detail:"\($present)/\($total) canonical KPI source files present"}
      ]
    }'
}

emit_health() {
  local ts; ts="$(now_iso)"
  local row_count=0
  local last_status=""
  local last_age=""
  if [[ -r "$LEDGER" ]]; then
    row_count="$(wc -l <"$LEDGER" 2>/dev/null | tr -d ' ')"
    [[ -z "$row_count" ]] && row_count=0
    if [[ "$row_count" -gt 0 ]]; then
      last_status="$(tail -n 1 "$LEDGER" 2>/dev/null | jq -r '.freshness_status // empty' 2>/dev/null || true)"
      last_age="$(tail -n 1 "$LEDGER" 2>/dev/null | jq -r '.freshness_age_hours // empty' 2>/dev/null || true)"
    fi
  fi
  local status="pass"
  [[ "$last_status" == "stale" ]] && status="warn"
  jq -nc --arg sv "$SCHEMA_VERSION.health" --arg ts "$ts" --arg status "$status" \
    --arg ledger "$LEDGER" --argjson row_count "${row_count:-0}" \
    --arg last_freshness "${last_status:-}" --arg last_age "${last_age:-}" \
    '{schema_version:$sv,command:"health",ts:$ts,status:$status,ledger:$ledger,ledger_row_count:$row_count,last_freshness_status:$last_freshness,last_freshness_age_hours:($last_age | tonumber? // null)}'
}

emit_validate() {
  local ts; ts="$(now_iso)"
  local rows=0 invalid=0
  if [[ -r "$LEDGER" ]]; then
    rows="$(wc -l <"$LEDGER" 2>/dev/null | tr -d ' ')"
    [[ -z "$rows" ]] && rows=0
    if [[ "$rows" -gt 0 ]]; then
      invalid="$(jq -c 'select((.schema_version // "") != "mobile-eats-end-user-health/v1")' "$LEDGER" 2>/dev/null | wc -l | tr -d ' ')"
      [[ -z "$invalid" ]] && invalid=0
    fi
  fi
  local status="pass"
  [[ "$invalid" -gt 0 ]] && status="violations"
  jq -nc --arg sv "$SCHEMA_VERSION.validate" --arg ts "$ts" --arg status "$status" \
    --argjson rows "${rows:-0}" --argjson invalid "${invalid:-0}" --arg ledger "$LEDGER" \
    '{schema_version:$sv,command:"validate",ts:$ts,status:$status,ledger:$ledger,row_count:$rows,invalid_row_count:$invalid,check:"every row has schema_version=mobile-eats-end-user-health/v1"}'
}

emit_audit() {
  local limit="${1:-20}"
  local ts; ts="$(now_iso)"
  if [[ ! -r "$LEDGER" ]]; then
    jq -nc --arg sv "$SCHEMA_VERSION.audit" --arg ts "$ts" --arg ledger "$LEDGER" \
      '{schema_version:$sv,command:"audit",ts:$ts,status:"missing",ledger:$ledger,row_count:0,recent:[]}'
    return 0
  fi
  local row_count
  row_count="$(wc -l <"$LEDGER" 2>/dev/null | tr -d ' ')"
  [[ -z "$row_count" ]] && row_count=0
  local recent='[]'
  if [[ "$row_count" -gt 0 ]]; then
    recent="$(tail -n "$limit" "$LEDGER" 2>/dev/null | jq -cs '.' 2>/dev/null || printf '%s' '[]')"
    [[ -z "$recent" ]] && recent='[]'
  fi
  local status="pass"
  [[ "$row_count" -eq 0 ]] && status="empty"
  jq -nc --arg sv "$SCHEMA_VERSION.audit" --arg ts "$ts" --arg status "$status" \
    --arg ledger "$LEDGER" --argjson row_count "$row_count" --argjson recent "$recent" \
    '{schema_version:$sv,command:"audit",ts:$ts,status:$status,ledger:$ledger,row_count:$row_count,recent:$recent}'
}

emit_why() {
  local topic="${1:-}"
  local body=""
  case "$topic" in
    ""|no-db-surface-yet)
      body='Mobile-eats production DB (Postgres via Supabase/Railway) is not exposed via flywheel substrate. KPIs (MRR/ARR/paying-owners/trial-to-paid/churn-30d, community-health) are server-rendered to Joshua admin pages but no flywheel-readable JSON snapshot endpoint exists. Until then, the proxy measurement is artifact-presence + mtime-freshness against the 4 canonical KPI source files.'
      ;;
    proxy-metrics)
      body='kpi_surfaces_present_count (4 source TS files) + kpi_tests_present_count (3 paired *.test.ts) + freshness_age_hours (hours since newest mtime) + freshness_status (fresh|stale vs 72h budget). These proxy for "are KPIs being maintained" until first-party DB telemetry is wired.'
      ;;
    step-4o-guardrail)
      body='Step-4o anti-pattern: probe surfaces the gap, does NOT auto-create beads or auto-dispatch fixes. Parent value-gap-probe.sh enforces this contract. Operator (or higher-level orchestrator) decides if a finding warrants a bead.'
      ;;
    *)
      body="unknown topic: $topic. known: no-db-surface-yet, proxy-metrics, step-4o-guardrail"
      ;;
  esac
  jq -nc --arg sv "$SCHEMA_VERSION" --arg topic "${topic:-no-db-surface-yet}" --arg body "$body" \
    '{schema_version:$sv,command:"why",topic:$topic,body:$body}'
}

emit_quickstart() {
  jq -nc --arg sv "$SCHEMA_VERSION" '{
    schema_version:$sv,
    command:"quickstart",
    status:"ok",
    steps:[
      {step:1,action:"check-doctor",command:"mobile-eats-end-user-health-probe.sh doctor --json"},
      {step:2,action:"dry-run-probe",command:"mobile-eats-end-user-health-probe.sh --json"},
      {step:3,action:"apply-with-idem-key",command:"mobile-eats-end-user-health-probe.sh --apply --idempotency-key meu-$(date +%Y%m%d) --json"},
      {step:4,action:"tail-recent-probes",command:"mobile-eats-end-user-health-probe.sh audit --json"}
    ],
    next_actions:["wire-first-party-db-snapshot-endpoint","escalate-on-freshness-stale-72h"]
  }'
}

emit_repair() {
  local scope="" mode="dry_run" idem_key=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --scope) scope="${2:-}"; shift 2 ;;
      --dry-run) mode="dry_run"; shift ;;
      --apply) mode="apply"; shift ;;
      --idempotency-key) idem_key="${2:-}"; shift 2 ;;
      --idempotency-key=*) idem_key="${1#--idempotency-key=}"; shift ;;
      --json) shift ;;
      --help|-h) printf 'repair --scope <ledger-prime> [--dry-run|--apply --idempotency-key KEY]\n'; exit 0 ;;
      "") shift ;;
      *) printf 'ERR: unknown repair arg %s\n' "$1" >&2; exit 2 ;;
    esac
  done
  if [[ -z "$scope" ]]; then
    printf '{"schema_version":"%s.repair","status":"refused","reason":"--scope required (ledger-prime)","exit_code":2}\n' "$SCHEMA_VERSION"
    exit 2
  fi
  if [[ "$mode" == "apply" && -z "$idem_key" ]]; then
    printf '{"schema_version":"%s.repair","status":"refused","mode":"apply","scope":"%s","reason":"--apply requires --idempotency-key","exit_code":3}\n' "$SCHEMA_VERSION" "$scope"
    exit 3
  fi
  local ts; ts="$(now_iso 2>/dev/null || date -u +%Y-%m-%dT%H:%M:%SZ)"
  case "$scope" in
    ledger-prime)
      local ledger_dir present_before present_after
      ledger_dir="$(dirname "$LEDGER")"
      present_before="$([[ -f "$LEDGER" ]] && printf true || printf false)"
      if [[ "$mode" == "apply" ]]; then
        mkdir -p "$ledger_dir" 2>/dev/null || true
        [[ -f "$LEDGER" ]] || : > "$LEDGER"
      fi
      present_after="$([[ -f "$LEDGER" ]] && printf true || printf false)"
      jq -nc --arg sv "$SCHEMA_VERSION.repair" --arg ts "$ts" --arg scope "$scope" --arg mode "$mode" \
        --arg ledger "$LEDGER" --arg key "$idem_key" \
        --argjson before "$present_before" --argjson after "$present_after" \
        '{schema_version:$sv,command:"repair",ts:$ts,status:"pass",scope:$scope,mode:$mode,idempotency_key:$key,ledger:$ledger,ledger_present_before:$before,ledger_present_after:$after}'
      ;;
    *)
      printf '{"schema_version":"%s.repair","status":"refused","scope":"%s","reason":"unknown scope; known: ledger-prime","exit_code":2}\n' "$SCHEMA_VERSION" "$scope"
      exit 2
      ;;
  esac
}

# Canonical no-dash subcommand intercept BEFORE main arg parser.
case "${1:-}" in
  doctor) shift; emit_canonical_doctor; exit 0 ;;
  health) shift; emit_health; exit 0 ;;
  validate) shift; emit_validate; exit 0 ;;
  audit)
    shift
    LIMIT=20
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --limit) LIMIT="${2:-20}"; shift 2 ;;
        --json) shift ;;
        "") shift ;;
        *) shift ;;
      esac
    done
    emit_audit "$LIMIT"
    exit 0
    ;;
  why)
    shift
    TOPIC=""
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --json) shift ;;
        "") shift ;;
        *) [[ -z "$TOPIC" ]] && TOPIC="$1"; shift ;;
      esac
    done
    emit_why "$TOPIC"
    exit 0
    ;;
  quickstart) shift; emit_quickstart; exit 0 ;;
  repair) shift; emit_repair "$@"; exit 0 ;;
esac

while [[ $# -gt 0 ]]; do
  case "$1" in
    --json) JSON_OUT=1; shift ;;
    --apply) APPLY=1; DRY_RUN=0; shift ;;
    --dry-run) DRY_RUN=1; APPLY=0; shift ;;
    --idempotency-key) IDEMPOTENCY_KEY="${2:-}"; shift 2 ;;
    --idempotency-key=*) IDEMPOTENCY_KEY="${1#--idempotency-key=}"; shift ;;
    --repo) REPO="${2:?}"; shift 2 ;;
    --ledger) LEDGER="${2:?}"; shift 2 ;;
    --doctor) MODE="doctor"; shift ;;
    --info) MODE="info"; shift ;;
    --schema) MODE="schema"; shift ;;
    --examples)
      shift
      if [[ "${1:-}" == "--json" ]]; then emit_examples_json; else emit_examples_text; fi
      exit 0
      ;;
    -h|--help) usage; exit 0 ;;
    *) echo "mobile-eats-end-user-health-probe.sh: unknown arg: $1" >&2; usage >&2; exit 64 ;;
  esac
done

# Canonical apply contract: --apply requires --idempotency-key.
if [[ $APPLY -eq 1 && -z "$IDEMPOTENCY_KEY" ]]; then
  printf '{"schema_version":"%s","status":"refused","mode":"apply","reason":"--apply requires --idempotency-key","exit_code":3}\n' "$SCHEMA_VERSION"
  exit 3
fi

if [[ $MODE == "run" && $APPLY -eq 0 && $DRY_RUN -eq 0 ]]; then
  DRY_RUN=1
fi

emit() {
  if [[ $JSON_OUT -eq 1 || $MODE == "info" || $MODE == "schema" || $MODE == "doctor" ]]; then
    printf '%s\n' "$1"
  fi
}

info_payload() {
  jq -nc \
    --arg version "$VERSION" \
    --arg script_version "$SCRIPT_VERSION" \
    --arg repo "$REPO" \
    --arg ledger "$LEDGER" \
    --argjson freshness_hours "$HOURS_FRESHNESS_BUDGET" \
    --argjson surfaces "$(printf '%s\n' "${KPI_SURFACES[@]}" | jq -R . | jq -s .)" \
    --argjson tests "$(printf '%s\n' "${KPI_TESTS[@]}" | jq -R . | jq -s .)" \
    '{
      name: "mobile-eats-end-user-health-probe.sh",
      command: "info",
      version: $version,
      script_version: $script_version,
      schema_version: "mobile-eats-end-user-health/v1",
      mode: "info",
      mobile_eats_repo: $repo,
      ledger: $ledger,
      kpi_surfaces: $surfaces,
      kpi_tests: $tests,
      freshness_budget_hours: $freshness_hours,
      modes: ["run","doctor","info","schema"],
      subcommands: ["doctor","health","validate","audit","why","repair","quickstart"],
      canonical_flags: ["--info","--schema","--examples","--json","--apply","--dry-run","--idempotency-key","--repo","--ledger","--doctor"],
      capabilities: [
        "kpi-surface-presence-probe",
        "kpi-test-presence-probe",
        "mtime-freshness-proxy",
        "no-db-surface-explicit-receipt",
        "freshness-budget-72h-default",
        "ledger-append-idempotent-via-idempotency-key",
        "step-4o-surface-only-no-auto-dispatch"
      ],
      apply_supported: true,
      dry_run_supported: true,
      idempotency_key_required_for_apply: true,
      mutates_state: true,
      env_vars: ["MOBILE_EATS_REPO","MOBILE_EATS_HEALTH_LEDGER","MOBILE_EATS_HEALTH_FRESHNESS_HOURS"],
      exit_codes: {"0":"ok","1":"domain","3":"refused-apply-without-idempotency-key","64":"usage"},
      owns: "flywheel-1rmp.7",
      duplicate_of_owns: ["flywheel-1rmp.17"],
      parent: "flywheel-1rmp",
      value_gap_dimension: "mobile-eats-end-user-health",
      meadows_tier: "#8 information flow",
      first_party_user_health: "no_db_surface_yet",
      first_party_no_surface_reason: "Mobile-eats production database (Postgres via Supabase / Railway) is not exposed via flywheel substrate; KPIs (MRR/ARR/paying-owners/trial-to-paid/churn-30d, community-health) are server-rendered for Joshua admin pages but no flywheel-readable JSON snapshot exists. The smallest recurring measurement is artifact-presence + mtime freshness against KPI source files until the app exports a thin flywheel-snapshot endpoint.",
      step_4o_anti_pattern_guardrail: "this probe surfaces; it does NOT auto-dispatch fixes",
      status: "ok"
    }'
}

schema_payload() {
  jq -nc '{
    schema_version: "mobile-eats-end-user-health/v1",
    command: "schema",
    input_schema: {
      type: "object",
      properties: {
        apply: {type:"boolean",description:"write probe row to ledger; requires idempotency_key"},
        dry_run: {type:"boolean"},
        idempotency_key: {type:"string",description:"required with --apply"},
        repo: {type:"string",description:"mobile-eats repo root"},
        ledger: {type:"string",description:"probe ledger path"}
      }
    },
    output_schema: {
      type: "object",
      required: ["schema_version","ts","repo","kpi_surfaces_present_count","kpi_surfaces_total","freshness_status"],
      properties: {
        schema_version: {const:"mobile-eats-end-user-health/v1"},
        ts: {type:"string",format:"date-time"},
        repo: {type:"string"},
        kpi_surfaces_present_count: {type:"integer",minimum:0},
        kpi_surfaces_total: {type:"integer",minimum:0},
        kpi_tests_present_count: {type:"integer",minimum:0},
        kpi_tests_total: {type:"integer",minimum:0},
        freshness_age_hours: {type:"integer",minimum:0},
        freshness_budget_hours: {type:"integer",minimum:1},
        freshness_status: {enum:["fresh","stale"]},
        actual_user_health: {enum:["no_db_surface_yet","computed","partial"]}
      }
    },
    ledger_row_required_fields: [
      "schema_version","ts","repo","kpi_surfaces_present_count",
      "kpi_surfaces_total","kpi_tests_present_count","kpi_tests_total",
      "newest_kpi_source_mtime","newest_kpi_source_path",
      "freshness_age_hours","freshness_budget_hours","freshness_status",
      "actual_user_health","actual_user_health_no_surface_reason",
      "kpi_surfaces","kpi_tests"
    ],
    proxy_metrics: [
      {"name":"kpi_surfaces_present_count","describes":"count of present KPI source TS files in the canonical 4-surface set"},
      {"name":"kpi_tests_present_count","describes":"count of paired *.test.ts files in the canonical 3-test set"},
      {"name":"freshness_age_hours","describes":"hours since newest mtime across KPI sources"},
      {"name":"freshness_status","describes":"fresh|stale verdict against freshness_budget_hours (default 72h)"}
    ],
    actual_user_health: {
      type: "string",
      enum: ["no_db_surface_yet","computed","partial"],
      no_surface_explanation: "Production DB not exposed via flywheel substrate; first-party MRR/ARR/churn telemetry is server-rendered to Joshua admin pages but not snapshot-export to a flywheel-readable JSON path."
    },
    surfaced_via: ["ledger:~/.local/state/flywheel/mobile-eats-end-user-health.jsonl","cli:mobile-eats-end-user-health-probe.sh","value-gap-probe parent ledger"],
    exit_codes: {"0":"ok","1":"domain","64":"usage"},
    mode: "schema",
    status: "ok"
  }'
}

doctor_payload() {
  local issues=()
  command -v jq >/dev/null 2>&1 || issues+=("jq_missing")
  [[ -d "$REPO" ]] || issues+=("repo_missing=$REPO")
  mkdir -p "$(dirname "$LEDGER")" 2>/dev/null
  [[ -w "$(dirname "$LEDGER")" ]] || issues+=("ledger_dir_not_writable=$(dirname "$LEDGER")")
  local issues_json
  if [[ ${#issues[@]} -gt 0 ]]; then
    issues_json=$(printf '%s\n' "${issues[@]}" | jq -R . | jq -s .)
  else
    issues_json='[]'
  fi
  jq -nc \
    --arg version "$VERSION" \
    --argjson issues "$issues_json" \
    '{
      version: $version,
      schema_version: "mobile-eats-end-user-health/v1",
      mode: "doctor",
      issues: $issues,
      status: (if ($issues|length)==0 then "ok" else "degraded" end)
    }'
}

# --- core measurement ---------------------------------------------------------
mtime_iso() {
  local p="$1"
  if [[ -f "$p" ]]; then
    stat -f '%Sm' -t '%Y-%m-%dT%H:%M:%SZ' "$p" 2>/dev/null
  fi
}

mtime_epoch() {
  local p="$1"
  if [[ -f "$p" ]]; then
    stat -f '%m' "$p" 2>/dev/null
  fi
}

run_pass() {
  local mode_label="$1"
  local now_epoch
  now_epoch=$(date -u +%s)

  local present_surfaces=0 total_surfaces=${#KPI_SURFACES[@]}
  local present_tests=0 total_tests=${#KPI_TESTS[@]}
  local newest_mtime=0 newest_path="" newest_iso=""
  local surfaces_json='[]' tests_json='[]'

  for rel in "${KPI_SURFACES[@]}"; do
    local abs="$REPO/$rel"
    local present="false"
    local mt_iso="" mt_ep=0
    if [[ -f "$abs" ]]; then
      present="true"
      present_surfaces=$((present_surfaces+1))
      mt_iso=$(mtime_iso "$abs")
      mt_ep=$(mtime_epoch "$abs")
      if (( mt_ep > newest_mtime )); then
        newest_mtime=$mt_ep
        newest_path="$rel"
        newest_iso="$mt_iso"
      fi
    fi
    surfaces_json=$(jq -c \
      --arg rel "$rel" --arg abs "$abs" --arg present "$present" \
      --arg mt "$mt_iso" \
      '. + [{path: $rel, abs: $abs, present: ($present == "true"), mtime: (if $mt == "" then null else $mt end)}]' \
      <<<"$surfaces_json")
  done

  for rel in "${KPI_TESTS[@]}"; do
    local abs="$REPO/$rel"
    local present="false"
    local mt_iso=""
    if [[ -f "$abs" ]]; then
      present="true"
      present_tests=$((present_tests+1))
      mt_iso=$(mtime_iso "$abs")
    fi
    tests_json=$(jq -c \
      --arg rel "$rel" --arg present "$present" --arg mt "$mt_iso" \
      '. + [{path: $rel, present: ($present == "true"), mtime: (if $mt == "" then null else $mt end)}]' \
      <<<"$tests_json")
  done

  local age_hours=999999 status_label="stale"
  if (( newest_mtime > 0 )); then
    age_hours=$(( (now_epoch - newest_mtime) / 3600 ))
    if (( age_hours <= HOURS_FRESHNESS_BUDGET )); then
      status_label="fresh"
    fi
  fi

  local row
  row=$(jq -nc \
    --arg ts "$(now_iso)" \
    --arg repo "$REPO" \
    --argjson present_surfaces "$present_surfaces" \
    --argjson total_surfaces "$total_surfaces" \
    --argjson present_tests "$present_tests" \
    --argjson total_tests "$total_tests" \
    --arg newest_mtime "$newest_iso" \
    --arg newest_path "$newest_path" \
    --argjson age_hours "$age_hours" \
    --argjson budget "$HOURS_FRESHNESS_BUDGET" \
    --arg status "$status_label" \
    --argjson surfaces "$surfaces_json" \
    --argjson tests "$tests_json" \
    '{
      schema_version: "mobile-eats-end-user-health/v1",
      ts: $ts,
      repo: $repo,
      kpi_surfaces_present_count: $present_surfaces,
      kpi_surfaces_total: $total_surfaces,
      kpi_tests_present_count: $present_tests,
      kpi_tests_total: $total_tests,
      newest_kpi_source_mtime: (if $newest_mtime == "" then null else $newest_mtime end),
      newest_kpi_source_path: (if $newest_path == "" then null else $newest_path end),
      freshness_age_hours: $age_hours,
      freshness_budget_hours: $budget,
      freshness_status: $status,
      actual_user_health: "no_db_surface_yet",
      actual_user_health_no_surface_reason: "Mobile-eats production DB (Postgres via Supabase/Railway) is not exposed via flywheel substrate; KPIs are server-rendered for Joshua admin pages but no flywheel-readable JSON snapshot exists. Smallest recurring proxy is artifact presence + mtime freshness against KPI source files; first-party DB telemetry wireup is a separate value-gap-followup bead under parent flywheel-1rmp.",
      kpi_surfaces: $surfaces,
      kpi_tests: $tests
    }')

  if [[ "$mode_label" == "apply" ]]; then
    mkdir -p "$(dirname "$LEDGER")" 2>/dev/null
    printf '%s\n' "$row" >> "$LEDGER" 2>/dev/null
  fi

  emit "$(printf '%s' "$row" | jq -c \
    --arg mode "$mode_label" --arg ledger "$LEDGER" \
    '{mode:$mode, ledger:$ledger} + .')"
  return 0
}

case "$MODE" in
  info)   emit "$(info_payload)"; exit 0 ;;
  schema) emit "$(schema_payload)"; exit 0 ;;
  doctor)
    payload="$(doctor_payload)"
    emit "$payload"
    [[ "$(printf '%s' "$payload" | jq -r .status)" == "ok" ]] && exit 0 || exit 1
    ;;
esac

if [[ $DRY_RUN -eq 1 ]]; then
  run_pass dry-run
  exit $?
fi
run_pass apply
exit $?
